[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_deps =
  heltecautomation/Heltec ESP32 Dev-Boards @ ^1.1.2

upload_port = COM3
monitor_port = COM3
build_flags = -I include